title: Zoey
description: Developer & Designer
author: Zoey
email: your-email@example.com
url: "https://zoey0227-code.github.io"

# Theme Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sidebar settings (This gives you the Rafa look)
show_sidebar: true
show_excerpts: true
